server:
  port: 80

spring:
  application:
    name: cloud-hystrix-order-service
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
    register-with-eureka: false
feign:
  hystrix:
    enabled: true

